# Experiment 5: Scattering Features + CNN Model




In [9]:
import sys
sys.path.append('../src')

from utils.reduce import reduce_pca
from utils.split import train_test_split, train_test_split_pytorch
from utils.UltrasoundDataset import UltrasoundDataset
from utils.Networks import  BasicBlock, Scattering2dResNet
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from torch.autograd import Variable
from kymatio.torch import Scattering2D
import argparse
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms
import torch.optim
import pickle
import pandas as pd
import numpy as np
import mlflow
import matplotlib.pyplot as plt

In [12]:
# create an experiment in mlruns if doesn't exit and specifiy where to log
mlflow.set_experiment('scattering_cnn_experiment')

## Upload Ultrasound images

In [10]:
with open('../data/02_interim/bmodes_steatosis_assessment_IJCARS.pickle', 'rb') as handle:
    df = pickle.load(handle)

In [11]:
M, N= 434, 636 # ultrasound image dimension

In [13]:
# split training and test (by making sure the 10 ultrasound images of one patient is in the same set)
train_data, test_data = train_test_split(df)

In [14]:
###############################################################################
# If a GPU is available, let's use it!
use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")
###############################################################################

# Create dataloader

In [ ]:
batch_size

In [8]:
# create dataset
# from https://github.com/python-engineer/pytorchTutorial/blob/master/09_dataloader.py

train_dataset = UltrasoundDataset(train_data)
test_dataset  = UltrasoundDataset(test_data)

# Load whole dataset with DataLoader
# shuffle: shuffle data, good for training
# num_workers: faster loading with multiple subprocesses
# !!! IF YOU GET AN ERROR DURING LOADING, SET num_workers TO 0 !!!
train_loader = DataLoader(dataset=train_dataset,
                          batch_size=20,
                          shuffle=True,
                          num_workers=2)
test_loader = DataLoader(dataset=test_dataset,
                          batch_size=5,
                          shuffle=True,
                          num_workers=2)


In [9]:
def conv3x3(in_planes, out_planes, stride=1):
    "3x3 convolution with padding"
    # in_planes = in_channels
    # out_planes = out_channels
    return nn.Conv2d(in_planes, out_planes, kernel_size=10, stride=stride,
                     padding=1, bias=False)


In [10]:
with open('./train_dataset.pickle', 'wb') as handle:
    pickle.dump(train_dataset, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('./test_dataset.pickle', 'wb') as handle:
    pickle.dump(test_dataset, handle, protocol=pickle.HIGHEST_PROTOCOL)

/home/mila/g/gauthies/.conda/envs/ultra/lib/python3.7/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)


## Defining scattering transformations

In [11]:
parser = argparse.ArgumentParser(description='CIFAR scattering  + hybrid examples')
parser.add_argument('--mode', type=int, default=1,help='scattering 1st or 2nd order')
parser.add_argument('--width', type=int, default=2,help='width factor for resnet')
args = parser.parse_args(args=[])

use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")

if args.mode == 1:
    scattering = Scattering2D(J=2, shape=(M, N), max_order=1)
    K = 17*1
else:
    scattering = Scattering2D(J=2, shape=(M, N))
    K = 81*1
if use_cuda:
    scattering = scattering.cuda()



## Training and Testing Functions

In [12]:
for batch_idx, (data, target) in enumerate(train_loader):
    print(scattering(data.to(device)).shape)
    break

torch.Size([20, 1, 17, 108, 159])


In [13]:
def train(model, device, train_loader, optimizer, epoch, scattering):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(scattering(data))
        loss = F.cross_entropy(output, target.type(torch.long))
        loss.backward()
        optimizer.step()
        if batch_idx % 5 == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))

def test(model, device, test_loader, scattering):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(scattering(data))
            print(target, output.max(1, keepdim=True)[1])
            test_loss += F.cross_entropy(output, target.type(torch.long), reduction='sum').item() # sum up batch loss
            pred = output.max(1, keepdim=True)[1] # get the index of the max log-probability
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.2f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))


## Training

In [24]:
model = Scattering2dResNet(K, args.width).to(device)

In [25]:
from tqdm import tqdm

In [28]:
test(model, device, test_loader, scattering)

tensor([1, 1, 1, 0, 0], device='cuda:0', dtype=torch.uint8) tensor([[1],
        [0],
        [0],
        [0],
        [0]], device='cuda:0')
tensor([1, 1, 0, 0, 1], device='cuda:0', dtype=torch.uint8) tensor([[0],
        [0],
        [0],
        [1],
        [1]], device='cuda:0')
tensor([1, 1, 1, 0, 1], device='cuda:0', dtype=torch.uint8) tensor([[1],
        [0],
        [0],
        [0],
        [0]], device='cuda:0')
tensor([1, 1, 1, 0, 0], device='cuda:0', dtype=torch.uint8) tensor([[1],
        [1],
        [1],
        [0],
        [1]], device='cuda:0')
tensor([1, 0, 1, 1, 1], device='cuda:0', dtype=torch.uint8) tensor([[0],
        [1],
        [1],
        [1],
        [0]], device='cuda:0')
tensor([1, 1, 1, 1, 1], device='cuda:0', dtype=torch.uint8) tensor([[1],
        [1],
        [1],
        [1],
        [1]], device='cuda:0')
tensor([0, 1, 0, 0, 1], device='cuda:0', dtype=torch.uint8) tensor([[1],
        [1],
        [1],
        [1],
        [0]], device='cuda:0')

In [27]:
# Optimizer
lr = 0.1
for epoch in tqdm(range(0, 100)):
    if epoch%20==0:
      optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=0.9,
                                  weight_decay=0.0005)
      lr*=0.2
    train(model, device, train_loader, optimizer, epoch+1, scattering)

test(model, device, test_loader, scattering)




  0%|          | 0/100 [00:00<?, ?it/s]

Train Epoch: 1 [0/490 (0%)]	Loss: 0.048296
Train Epoch: 1 [100/490 (20%)]	Loss: 0.318545
Train Epoch: 1 [200/490 (40%)]	Loss: 0.239580
Train Epoch: 1 [300/490 (60%)]	Loss: 0.950013
Train Epoch: 1 [400/490 (80%)]	Loss: 0.384695



  1%|          | 1/100 [00:08<13:23,  8.12s/it]

Train Epoch: 2 [0/490 (0%)]	Loss: 0.653871
Train Epoch: 2 [100/490 (20%)]	Loss: 0.284926
Train Epoch: 2 [200/490 (40%)]	Loss: 0.304205
Train Epoch: 2 [300/490 (60%)]	Loss: 0.510675
Train Epoch: 2 [400/490 (80%)]	Loss: 0.293771



  2%|▏         | 2/100 [00:16<13:13,  8.10s/it]

Train Epoch: 3 [0/490 (0%)]	Loss: 0.328335
Train Epoch: 3 [100/490 (20%)]	Loss: 0.134635
Train Epoch: 3 [200/490 (40%)]	Loss: 0.266044
Train Epoch: 3 [300/490 (60%)]	Loss: 0.141956
Train Epoch: 3 [400/490 (80%)]	Loss: 0.152533



  3%|▎         | 3/100 [00:24<13:04,  8.09s/it]

Train Epoch: 4 [0/490 (0%)]	Loss: 0.439558
Train Epoch: 4 [100/490 (20%)]	Loss: 0.319188
Train Epoch: 4 [200/490 (40%)]	Loss: 0.559839
Train Epoch: 4 [300/490 (60%)]	Loss: 0.976671
Train Epoch: 4 [400/490 (80%)]	Loss: 0.808896



  4%|▍         | 4/100 [00:32<12:55,  8.08s/it]

Train Epoch: 5 [0/490 (0%)]	Loss: 0.317945
Train Epoch: 5 [100/490 (20%)]	Loss: 0.752270
Train Epoch: 5 [200/490 (40%)]	Loss: 0.497464
Train Epoch: 5 [300/490 (60%)]	Loss: 0.514561
Train Epoch: 5 [400/490 (80%)]	Loss: 0.207687



  5%|▌         | 5/100 [00:40<12:47,  8.07s/it]

Train Epoch: 6 [0/490 (0%)]	Loss: 0.611090
Train Epoch: 6 [100/490 (20%)]	Loss: 0.324264
Train Epoch: 6 [200/490 (40%)]	Loss: 0.239355
Train Epoch: 6 [300/490 (60%)]	Loss: 0.360849
Train Epoch: 6 [400/490 (80%)]	Loss: 0.399189



  6%|▌         | 6/100 [00:48<12:38,  8.07s/it]

Train Epoch: 7 [0/490 (0%)]	Loss: 0.139543
Train Epoch: 7 [100/490 (20%)]	Loss: 0.115788
Train Epoch: 7 [200/490 (40%)]	Loss: 0.212053
Train Epoch: 7 [300/490 (60%)]	Loss: 0.233316
Train Epoch: 7 [400/490 (80%)]	Loss: 0.087065



  7%|▋         | 7/100 [00:56<12:31,  8.08s/it]

Train Epoch: 8 [0/490 (0%)]	Loss: 0.038863
Train Epoch: 8 [100/490 (20%)]	Loss: 0.182482
Train Epoch: 8 [200/490 (40%)]	Loss: 0.450166
Train Epoch: 8 [300/490 (60%)]	Loss: 0.822697
Train Epoch: 8 [400/490 (80%)]	Loss: 0.420881



  8%|▊         | 8/100 [01:04<12:22,  8.07s/it]

Train Epoch: 9 [0/490 (0%)]	Loss: 0.494144
Train Epoch: 9 [100/490 (20%)]	Loss: 0.332868
Train Epoch: 9 [200/490 (40%)]	Loss: 0.107931
Train Epoch: 9 [300/490 (60%)]	Loss: 0.421030
Train Epoch: 9 [400/490 (80%)]	Loss: 0.090536



  9%|▉         | 9/100 [01:12<12:14,  8.08s/it]

Train Epoch: 10 [0/490 (0%)]	Loss: 0.254283
Train Epoch: 10 [100/490 (20%)]	Loss: 0.195243
Train Epoch: 10 [200/490 (40%)]	Loss: 0.398842
Train Epoch: 10 [300/490 (60%)]	Loss: 0.051353
Train Epoch: 10 [400/490 (80%)]	Loss: 0.155275



 10%|█         | 10/100 [01:20<12:07,  8.08s/it]

Train Epoch: 11 [0/490 (0%)]	Loss: 0.199874
Train Epoch: 11 [100/490 (20%)]	Loss: 0.130654
Train Epoch: 11 [200/490 (40%)]	Loss: 0.053462
Train Epoch: 11 [300/490 (60%)]	Loss: 0.066734
Train Epoch: 11 [400/490 (80%)]	Loss: 0.094651



 11%|█         | 11/100 [01:28<11:59,  8.08s/it]

Train Epoch: 12 [0/490 (0%)]	Loss: 0.141400
Train Epoch: 12 [100/490 (20%)]	Loss: 0.058916
Train Epoch: 12 [200/490 (40%)]	Loss: 0.211548
Train Epoch: 12 [300/490 (60%)]	Loss: 0.033687
Train Epoch: 12 [400/490 (80%)]	Loss: 0.050299



 12%|█▏        | 12/100 [01:36<11:51,  8.08s/it]

Train Epoch: 13 [0/490 (0%)]	Loss: 0.082597
Train Epoch: 13 [100/490 (20%)]	Loss: 0.123899
Train Epoch: 13 [200/490 (40%)]	Loss: 0.203499
Train Epoch: 13 [300/490 (60%)]	Loss: 0.209497
Train Epoch: 13 [400/490 (80%)]	Loss: 0.259059



 13%|█▎        | 13/100 [01:44<11:42,  8.08s/it]

Train Epoch: 14 [0/490 (0%)]	Loss: 0.361975
Train Epoch: 14 [100/490 (20%)]	Loss: 0.282719
Train Epoch: 14 [200/490 (40%)]	Loss: 0.066732
Train Epoch: 14 [300/490 (60%)]	Loss: 0.197497
Train Epoch: 14 [400/490 (80%)]	Loss: 0.108683



 14%|█▍        | 14/100 [01:53<11:34,  8.07s/it]

Train Epoch: 15 [0/490 (0%)]	Loss: 0.206756
Train Epoch: 15 [100/490 (20%)]	Loss: 0.063019
Train Epoch: 15 [200/490 (40%)]	Loss: 0.110515
Train Epoch: 15 [300/490 (60%)]	Loss: 0.071395
Train Epoch: 15 [400/490 (80%)]	Loss: 0.056919



 15%|█▌        | 15/100 [02:01<11:26,  8.07s/it]

Train Epoch: 16 [0/490 (0%)]	Loss: 0.060248
Train Epoch: 16 [100/490 (20%)]	Loss: 0.040397
Train Epoch: 16 [200/490 (40%)]	Loss: 0.064817
Train Epoch: 16 [300/490 (60%)]	Loss: 0.020416
Train Epoch: 16 [400/490 (80%)]	Loss: 0.138013



 16%|█▌        | 16/100 [02:09<11:18,  8.08s/it]

Train Epoch: 17 [0/490 (0%)]	Loss: 0.063409
Train Epoch: 17 [100/490 (20%)]	Loss: 0.029131
Train Epoch: 17 [200/490 (40%)]	Loss: 0.085534
Train Epoch: 17 [300/490 (60%)]	Loss: 0.057925
Train Epoch: 17 [400/490 (80%)]	Loss: 0.228691



 17%|█▋        | 17/100 [02:17<11:10,  8.08s/it]

Train Epoch: 18 [0/490 (0%)]	Loss: 0.133744
Train Epoch: 18 [100/490 (20%)]	Loss: 0.136890
Train Epoch: 18 [200/490 (40%)]	Loss: 0.021394
Train Epoch: 18 [300/490 (60%)]	Loss: 0.024967
Train Epoch: 18 [400/490 (80%)]	Loss: 0.154552



 18%|█▊        | 18/100 [02:25<11:02,  8.08s/it]

Train Epoch: 19 [0/490 (0%)]	Loss: 0.069390
Train Epoch: 19 [100/490 (20%)]	Loss: 0.032352
Train Epoch: 19 [200/490 (40%)]	Loss: 0.261218
Train Epoch: 19 [300/490 (60%)]	Loss: 0.118742
Train Epoch: 19 [400/490 (80%)]	Loss: 1.061881



 19%|█▉        | 19/100 [02:33<10:54,  8.08s/it]

Train Epoch: 20 [0/490 (0%)]	Loss: 0.491835
Train Epoch: 20 [100/490 (20%)]	Loss: 0.414626
Train Epoch: 20 [200/490 (40%)]	Loss: 0.081289
Train Epoch: 20 [300/490 (60%)]	Loss: 0.068249
Train Epoch: 20 [400/490 (80%)]	Loss: 0.053021



 20%|██        | 20/100 [02:41<10:46,  8.08s/it]

Train Epoch: 21 [0/490 (0%)]	Loss: 0.083245
Train Epoch: 21 [100/490 (20%)]	Loss: 0.059188
Train Epoch: 21 [200/490 (40%)]	Loss: 0.028290
Train Epoch: 21 [300/490 (60%)]	Loss: 0.096822
Train Epoch: 21 [400/490 (80%)]	Loss: 0.110014



 21%|██        | 21/100 [02:49<10:37,  8.08s/it]

Train Epoch: 22 [0/490 (0%)]	Loss: 0.068055
Train Epoch: 22 [100/490 (20%)]	Loss: 0.038509
Train Epoch: 22 [200/490 (40%)]	Loss: 0.033684
Train Epoch: 22 [300/490 (60%)]	Loss: 0.044756
Train Epoch: 22 [400/490 (80%)]	Loss: 0.070400



 22%|██▏       | 22/100 [02:57<10:30,  8.08s/it]

Train Epoch: 23 [0/490 (0%)]	Loss: 0.049528
Train Epoch: 23 [100/490 (20%)]	Loss: 0.031394
Train Epoch: 23 [200/490 (40%)]	Loss: 0.029764
Train Epoch: 23 [300/490 (60%)]	Loss: 0.019006
Train Epoch: 23 [400/490 (80%)]	Loss: 0.065310



 23%|██▎       | 23/100 [03:05<10:22,  8.09s/it]

Train Epoch: 24 [0/490 (0%)]	Loss: 0.029185
Train Epoch: 24 [100/490 (20%)]	Loss: 0.033664
Train Epoch: 24 [200/490 (40%)]	Loss: 0.047092
Train Epoch: 24 [300/490 (60%)]	Loss: 0.027430
Train Epoch: 24 [400/490 (80%)]	Loss: 0.043194



 24%|██▍       | 24/100 [03:13<10:14,  8.09s/it]

Train Epoch: 25 [0/490 (0%)]	Loss: 0.017751
Train Epoch: 25 [100/490 (20%)]	Loss: 0.030548
Train Epoch: 25 [200/490 (40%)]	Loss: 0.022565
Train Epoch: 25 [300/490 (60%)]	Loss: 0.061847
Train Epoch: 25 [400/490 (80%)]	Loss: 0.022102



 25%|██▌       | 25/100 [03:21<10:07,  8.09s/it]

Train Epoch: 26 [0/490 (0%)]	Loss: 0.059656
Train Epoch: 26 [100/490 (20%)]	Loss: 0.018100
Train Epoch: 26 [200/490 (40%)]	Loss: 0.006776
Train Epoch: 26 [300/490 (60%)]	Loss: 0.025254
Train Epoch: 26 [400/490 (80%)]	Loss: 0.034177



 26%|██▌       | 26/100 [03:30<09:58,  8.09s/it]

Train Epoch: 27 [0/490 (0%)]	Loss: 0.033124
Train Epoch: 27 [100/490 (20%)]	Loss: 0.085619
Train Epoch: 27 [200/490 (40%)]	Loss: 0.011277
Train Epoch: 27 [300/490 (60%)]	Loss: 0.018121
Train Epoch: 27 [400/490 (80%)]	Loss: 0.025063



 27%|██▋       | 27/100 [03:38<09:50,  8.09s/it]

Train Epoch: 28 [0/490 (0%)]	Loss: 0.005662
Train Epoch: 28 [100/490 (20%)]	Loss: 0.123811
Train Epoch: 28 [200/490 (40%)]	Loss: 0.036048
Train Epoch: 28 [300/490 (60%)]	Loss: 0.027784
Train Epoch: 28 [400/490 (80%)]	Loss: 0.028228



 28%|██▊       | 28/100 [03:46<09:42,  8.09s/it]

Train Epoch: 29 [0/490 (0%)]	Loss: 0.022832
Train Epoch: 29 [100/490 (20%)]	Loss: 0.020477
Train Epoch: 29 [200/490 (40%)]	Loss: 0.010852
Train Epoch: 29 [300/490 (60%)]	Loss: 0.019121
Train Epoch: 29 [400/490 (80%)]	Loss: 0.032262



 29%|██▉       | 29/100 [03:54<09:34,  8.09s/it]

Train Epoch: 30 [0/490 (0%)]	Loss: 0.038119
Train Epoch: 30 [100/490 (20%)]	Loss: 0.027844
Train Epoch: 30 [200/490 (40%)]	Loss: 0.076605
Train Epoch: 30 [300/490 (60%)]	Loss: 0.006257
Train Epoch: 30 [400/490 (80%)]	Loss: 0.039330



 30%|███       | 30/100 [04:02<09:25,  8.09s/it]

Train Epoch: 31 [0/490 (0%)]	Loss: 0.018575
Train Epoch: 31 [100/490 (20%)]	Loss: 0.027173
Train Epoch: 31 [200/490 (40%)]	Loss: 0.038416
Train Epoch: 31 [300/490 (60%)]	Loss: 0.012995
Train Epoch: 31 [400/490 (80%)]	Loss: 0.006833



 31%|███       | 31/100 [04:10<09:17,  8.08s/it]

Train Epoch: 32 [0/490 (0%)]	Loss: 0.023793
Train Epoch: 32 [100/490 (20%)]	Loss: 0.011679
Train Epoch: 32 [200/490 (40%)]	Loss: 0.009168
Train Epoch: 32 [300/490 (60%)]	Loss: 0.013932
Train Epoch: 32 [400/490 (80%)]	Loss: 0.026427



 32%|███▏      | 32/100 [04:18<09:09,  8.08s/it]

Train Epoch: 33 [0/490 (0%)]	Loss: 0.007133
Train Epoch: 33 [100/490 (20%)]	Loss: 0.051532
Train Epoch: 33 [200/490 (40%)]	Loss: 0.021881
Train Epoch: 33 [300/490 (60%)]	Loss: 0.011441
Train Epoch: 33 [400/490 (80%)]	Loss: 0.032280



 33%|███▎      | 33/100 [04:26<09:01,  8.08s/it]

Train Epoch: 34 [0/490 (0%)]	Loss: 0.023942
Train Epoch: 34 [100/490 (20%)]	Loss: 0.022019
Train Epoch: 34 [200/490 (40%)]	Loss: 0.058078
Train Epoch: 34 [300/490 (60%)]	Loss: 0.010230
Train Epoch: 34 [400/490 (80%)]	Loss: 0.007897



 34%|███▍      | 34/100 [04:34<08:53,  8.08s/it]

Train Epoch: 35 [0/490 (0%)]	Loss: 0.004061
Train Epoch: 35 [100/490 (20%)]	Loss: 0.014852
Train Epoch: 35 [200/490 (40%)]	Loss: 0.077533
Train Epoch: 35 [300/490 (60%)]	Loss: 0.011691
Train Epoch: 35 [400/490 (80%)]	Loss: 0.014075



 35%|███▌      | 35/100 [04:42<08:45,  8.08s/it]

Train Epoch: 36 [0/490 (0%)]	Loss: 0.013753
Train Epoch: 36 [100/490 (20%)]	Loss: 0.074630
Train Epoch: 36 [200/490 (40%)]	Loss: 0.007605
Train Epoch: 36 [300/490 (60%)]	Loss: 0.012947
Train Epoch: 36 [400/490 (80%)]	Loss: 0.008119



 36%|███▌      | 36/100 [04:50<08:37,  8.08s/it]

Train Epoch: 37 [0/490 (0%)]	Loss: 0.014302
Train Epoch: 37 [100/490 (20%)]	Loss: 0.020887
Train Epoch: 37 [200/490 (40%)]	Loss: 0.011535
Train Epoch: 37 [300/490 (60%)]	Loss: 0.013069
Train Epoch: 37 [400/490 (80%)]	Loss: 0.008707



 37%|███▋      | 37/100 [04:58<08:29,  8.08s/it]

Train Epoch: 38 [0/490 (0%)]	Loss: 0.012406
Train Epoch: 38 [100/490 (20%)]	Loss: 0.010253
Train Epoch: 38 [200/490 (40%)]	Loss: 0.032811
Train Epoch: 38 [300/490 (60%)]	Loss: 0.004039
Train Epoch: 38 [400/490 (80%)]	Loss: 0.067076



 38%|███▊      | 38/100 [05:07<08:20,  8.08s/it]

Train Epoch: 39 [0/490 (0%)]	Loss: 0.011469
Train Epoch: 39 [100/490 (20%)]	Loss: 0.020157
Train Epoch: 39 [200/490 (40%)]	Loss: 0.009759
Train Epoch: 39 [300/490 (60%)]	Loss: 0.016177
Train Epoch: 39 [400/490 (80%)]	Loss: 0.005673



 39%|███▉      | 39/100 [05:15<08:13,  8.08s/it]

Train Epoch: 40 [0/490 (0%)]	Loss: 0.006138
Train Epoch: 40 [100/490 (20%)]	Loss: 0.003864
Train Epoch: 40 [200/490 (40%)]	Loss: 0.012299
Train Epoch: 40 [300/490 (60%)]	Loss: 0.018879
Train Epoch: 40 [400/490 (80%)]	Loss: 0.009259



 40%|████      | 40/100 [05:23<08:05,  8.09s/it]

Train Epoch: 41 [0/490 (0%)]	Loss: 0.004389
Train Epoch: 41 [100/490 (20%)]	Loss: 0.008355
Train Epoch: 41 [200/490 (40%)]	Loss: 0.007572
Train Epoch: 41 [300/490 (60%)]	Loss: 0.011791
Train Epoch: 41 [400/490 (80%)]	Loss: 0.054201



 41%|████      | 41/100 [05:31<07:57,  8.09s/it]

Train Epoch: 42 [0/490 (0%)]	Loss: 0.008774
Train Epoch: 42 [100/490 (20%)]	Loss: 0.011736
Train Epoch: 42 [200/490 (40%)]	Loss: 0.050724
Train Epoch: 42 [300/490 (60%)]	Loss: 0.017340
Train Epoch: 42 [400/490 (80%)]	Loss: 0.018878



 42%|████▏     | 42/100 [05:39<07:49,  8.09s/it]

Train Epoch: 43 [0/490 (0%)]	Loss: 0.018691
Train Epoch: 43 [100/490 (20%)]	Loss: 0.032518
Train Epoch: 43 [200/490 (40%)]	Loss: 0.007072
Train Epoch: 43 [300/490 (60%)]	Loss: 0.030528
Train Epoch: 43 [400/490 (80%)]	Loss: 0.004484



 43%|████▎     | 43/100 [05:47<07:41,  8.09s/it]

Train Epoch: 44 [0/490 (0%)]	Loss: 0.013428
Train Epoch: 44 [100/490 (20%)]	Loss: 0.004776
Train Epoch: 44 [200/490 (40%)]	Loss: 0.018246
Train Epoch: 44 [300/490 (60%)]	Loss: 0.011422
Train Epoch: 44 [400/490 (80%)]	Loss: 0.033490



 44%|████▍     | 44/100 [05:55<07:33,  8.10s/it]

Train Epoch: 45 [0/490 (0%)]	Loss: 0.004327
Train Epoch: 45 [100/490 (20%)]	Loss: 0.007497
Train Epoch: 45 [200/490 (40%)]	Loss: 0.005887
Train Epoch: 45 [300/490 (60%)]	Loss: 0.006461
Train Epoch: 45 [400/490 (80%)]	Loss: 0.002381



 45%|████▌     | 45/100 [06:03<07:25,  8.10s/it]

Train Epoch: 46 [0/490 (0%)]	Loss: 0.007248
Train Epoch: 46 [100/490 (20%)]	Loss: 0.005624
Train Epoch: 46 [200/490 (40%)]	Loss: 0.006346
Train Epoch: 46 [300/490 (60%)]	Loss: 0.003954
Train Epoch: 46 [400/490 (80%)]	Loss: 0.004343



 46%|████▌     | 46/100 [06:11<07:17,  8.10s/it]

Train Epoch: 47 [0/490 (0%)]	Loss: 0.010192
Train Epoch: 47 [100/490 (20%)]	Loss: 0.003215
Train Epoch: 47 [200/490 (40%)]	Loss: 0.005848
Train Epoch: 47 [300/490 (60%)]	Loss: 0.004483
Train Epoch: 47 [400/490 (80%)]	Loss: 0.003397



 47%|████▋     | 47/100 [06:19<07:09,  8.10s/it]

Train Epoch: 48 [0/490 (0%)]	Loss: 0.006691
Train Epoch: 48 [100/490 (20%)]	Loss: 0.003676
Train Epoch: 48 [200/490 (40%)]	Loss: 0.007161


KeyboardInterrupt: 

# Run Mlflow to see results

`!mlflow ui`

Should launch something like this:



In [ ]:
# !mlflow ui